# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 755)
        MainWindow.setMinimumSize(QtCore.QSize(1041, 646))
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"QWidget {\n"
"    color: rgb(0, 0, 0); /* Change this line to set text color to black */\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid #25273d;\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {    \n"
"    background-color:#25273d;\n"
"    border: 1px solid #25273d;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {    \n"
"    background-color:#1c172e;\n"
"}\n"
"#topLogo {\n"
"    background-color:#1c172e;\n"
"    background-repeat: no-repeat;\n"
"    background-position: left; /* or background-position: 0; */\n"
"    \n"
"   \n"
"}\n"
"\n"
"#titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
"#titleLeftDescription { font: 8pt \"Segoe UI\"; color: rgb(189, 147, 249); }\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding-left: 22px;\n"
"}\n"
"#topMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#topMenu .QPushButton:pressed {    \n"
"background-color:rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#bottomMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#bottomMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#bottomMenu .QPushButton:pressed {    \n"
"background-color:rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#leftMenuFrame{\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color: rgb(37, 41, 48);\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#toggleButton:pressed {\n"
"background-color:rgb(85, 170, 255);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo { padding-left: 10px; }\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel { color: rgb(255, 255, 255); }\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#extraCloseColumnBtn:hover { background-color: rgb(196, 161, 249); border-style: solid; border-radius: 4px; }\n"
"#extraCloseColumnBtn:pressed { background-color: rgb(180, 141, 238); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Extra Content */\n"
"#extraContent{\n"
"    border-top: 3px solid rgb(40, 44, 52);\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#extraTopMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#extraTopMenu .QPushButton:pressed {    \n"
"background-color:rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg{    \n"
"    background-color:#1c172e;\n"
"\n"
"}\n"
"#contentBottom{\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#rightButtons .QPushButton:hover { background-color: rgb(44, 49, 57); border-style: solid; border-radius: 4px; }\n"
"#rightButtons .QPushButton:pressed { background-color: rgb(23, 26, 30); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox { background-color: rgb(44, 49, 58); }\n"
"#themeSettingsTopDetail { background-color:rgb(85, 170, 255);\n"
" }\n"
"\n"
"/* Bottom Bar */\n"
"#bottomBar {    background-color:#1c172e;\n"
" }\n"
"#bottomBar QLabel { font-size: 11px; color: rgb(113, 126, 149); padding-left: 10px; padding-right: 10px; padding-bottom: 2px; }\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"#contentSettings .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#contentSettings .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#contentSettings .QPushButton:pressed {    \n"
"background-color:rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {    \n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"background-color:rgb(85, 170, 255);\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(33, 37, 43);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    border-radius: 5px;\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid transparent;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background:rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"background:rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"background-color:rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"background-color:rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"QLabel{\n"
"color:white;}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"color:rgb(85, 170, 255);\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"#pagesContainer QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"#pagesContainer QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"#pagesContainer QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(0, 0, 0, 0)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        self.bgApp.setStyleSheet("")
        self.bgApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(self.bgApp)
        self.leftMenuBg.setEnabled(True)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLogoInfo = QtWidgets.QFrame(self.leftMenuBg)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 50))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topLogoInfo.setStyleSheet("")
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.titleLeftApp = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftApp.setGeometry(QtCore.QRect(70, 8, 160, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.titleLeftApp.setFont(font)
        self.titleLeftApp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLeftApp.setObjectName("titleLeftApp")
        self.titleLeftDescription = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftDescription.setGeometry(QtCore.QRect(70, 27, 160, 16))
        self.titleLeftDescription.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLeftDescription.setFont(font)
        self.titleLeftDescription.setText("")
        self.titleLeftDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLeftDescription.setObjectName("titleLeftDescription")
        self.label = QtWidgets.QLabel(self.topLogoInfo)
        self.label.setGeometry(QtCore.QRect(0, 5, 61, 41))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBg)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.toggleBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.toggleBox.setMaximumSize(QtCore.QSize(16777215, 15))
        self.toggleBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggleBox.setObjectName("toggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalMenuLayout.addWidget(self.toggleBox)
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnHome = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome.sizePolicy().hasHeightForWidth())
        self.btnHome.setSizePolicy(sizePolicy)
        self.btnHome.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnHome.setFont(font)
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHome.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnHome.setStyleSheet("")
        self.btnHome.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHome.setIcon(icon)
        self.btnHome.setObjectName("btnHome")
        self.verticalLayout_8.addWidget(self.btnHome)
        self.btnTimeTracking = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTimeTracking.sizePolicy().hasHeightForWidth())
        self.btnTimeTracking.setSizePolicy(sizePolicy)
        self.btnTimeTracking.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnTimeTracking.setFont(font)
        self.btnTimeTracking.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTimeTracking.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnTimeTracking.setStyleSheet("")
        self.btnTimeTracking.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTimeTracking.setIcon(icon1)
        self.btnTimeTracking.setObjectName("btnTimeTracking")
        self.verticalLayout_8.addWidget(self.btnTimeTracking)
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignTop)
        self.bottomMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.bottomMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomMenu.setObjectName("bottomMenu")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bottomMenu)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalMenuLayout.addWidget(self.bottomMenu, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.extraLeftBox = QtWidgets.QFrame(self.bgApp)
        self.extraLeftBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraLeftBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraLeftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraLeftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraLeftBox.setObjectName("extraLeftBox")
        self.extraColumLayout = QtWidgets.QVBoxLayout(self.extraLeftBox)
        self.extraColumLayout.setContentsMargins(0, 0, 0, 0)
        self.extraColumLayout.setSpacing(0)
        self.extraColumLayout.setObjectName("extraColumLayout")
        self.extraTopBg = QtWidgets.QFrame(self.extraLeftBox)
        self.extraTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.extraTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.extraTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraTopBg.setObjectName("extraTopBg")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.extraTopBg)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.extraTopLayout = QtWidgets.QGridLayout()
        self.extraTopLayout.setContentsMargins(10, -1, 10, -1)
        self.extraTopLayout.setHorizontalSpacing(10)
        self.extraTopLayout.setVerticalSpacing(0)
        self.extraTopLayout.setObjectName("extraTopLayout")
        self.extraIcon = QtWidgets.QFrame(self.extraTopBg)
        self.extraIcon.setMinimumSize(QtCore.QSize(20, 0))
        self.extraIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.extraIcon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraIcon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraIcon.setObjectName("extraIcon")
        self.extraTopLayout.addWidget(self.extraIcon, 0, 0, 1, 1)
        self.extraLabel = QtWidgets.QLabel(self.extraTopBg)
        self.extraLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.extraLabel.setObjectName("extraLabel")
        self.extraTopLayout.addWidget(self.extraLabel, 0, 1, 1, 1)
        self.extraCloseColumnBtn = QtWidgets.QPushButton(self.extraTopBg)
        self.extraCloseColumnBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.extraCloseColumnBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.extraCloseColumnBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.extraCloseColumnBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extraCloseColumnBtn.setIcon(icon2)
        self.extraCloseColumnBtn.setIconSize(QtCore.QSize(20, 20))
        self.extraCloseColumnBtn.setObjectName("extraCloseColumnBtn")
        self.extraTopLayout.addWidget(self.extraCloseColumnBtn, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.extraTopLayout)
        self.extraColumLayout.addWidget(self.extraTopBg)
        self.extraContent = QtWidgets.QFrame(self.extraLeftBox)
        self.extraContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraContent.setObjectName("extraContent")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.extraContent)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.extraTopMenu = QtWidgets.QFrame(self.extraContent)
        self.extraTopMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraTopMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraTopMenu.setObjectName("extraTopMenu")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.extraTopMenu)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_share = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_share.sizePolicy().hasHeightForWidth())
        self.btn_share.setSizePolicy(sizePolicy)
        self.btn_share.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_share.setFont(font)
        self.btn_share.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_share.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_share.setStyleSheet("background-image: url(:/icons/images/icons/cil-share-boxed.png);")
        self.btn_share.setObjectName("btn_share")
        self.verticalLayout_11.addWidget(self.btn_share)
        self.btn_adjustments = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_adjustments.sizePolicy().hasHeightForWidth())
        self.btn_adjustments.setSizePolicy(sizePolicy)
        self.btn_adjustments.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_adjustments.setFont(font)
        self.btn_adjustments.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_adjustments.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_adjustments.setStyleSheet("background-image: url(:/icons/images/icons/cil-equalizer.png);")
        self.btn_adjustments.setObjectName("btn_adjustments")
        self.verticalLayout_11.addWidget(self.btn_adjustments)
        self.btn_more = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_more.sizePolicy().hasHeightForWidth())
        self.btn_more.setSizePolicy(sizePolicy)
        self.btn_more.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_more.setFont(font)
        self.btn_more.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_more.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_more.setStyleSheet("background-image: url(:/icons/images/icons/cil-layers.png);")
        self.btn_more.setObjectName("btn_more")
        self.verticalLayout_11.addWidget(self.btn_more)
        self.verticalLayout_12.addWidget(self.extraTopMenu, 0, QtCore.Qt.AlignTop)
        self.extraCenter = QtWidgets.QFrame(self.extraContent)
        self.extraCenter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraCenter.setObjectName("extraCenter")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.extraCenter)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.textEdit = QtWidgets.QTextEdit(self.extraCenter)
        self.textEdit.setMinimumSize(QtCore.QSize(222, 0))
        self.textEdit.setStyleSheet("background: transparent;")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_10.addWidget(self.textEdit)
        self.verticalLayout_12.addWidget(self.extraCenter)
        self.extraBottom = QtWidgets.QFrame(self.extraContent)
        self.extraBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraBottom.setObjectName("extraBottom")
        self.verticalLayout_12.addWidget(self.extraBottom)
        self.extraColumLayout.addWidget(self.extraContent)
        self.appLayout.addWidget(self.extraLeftBox)
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon3)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon4)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        self.closeAppBtn.setIcon(icon2)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBg)
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        self.pagesContainer.setStyleSheet("")
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pagesContainer.setObjectName("pagesContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pagesContainer)
        self.verticalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stackedWidget = QtWidgets.QStackedWidget(self.pagesContainer)
        self.stackedWidget.setStyleSheet("    background-color:#25273d;\n"
"    border: 1px solid #25273d;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.stackedWidget.addWidget(self.dashboard)
        self.timePage = QtWidgets.QWidget()
        self.timePage.setObjectName("timePage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.timePage)
        self.verticalLayout.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.timePage)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnUpdate = QtWidgets.QPushButton(self.frame)
        self.btnUpdate.setMinimumSize(QtCore.QSize(170, 35))
        self.btnUpdate.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnUpdate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUpdate.setStyleSheet("\n"
"#btnUpdate{\n"
"\n"
"background-color:#3c2d96;\n"
"font: 75 12pt \"Arial\";\n"
"color:white;\n"
"}\n"
"#btnUpdate:hover {\n"
"background-color:rgb(85, 170, 255);\n"
"}")
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout_6.addWidget(self.btnUpdate)
        self.verticalLayout.addWidget(self.frame)
        self.MainInputFrame = QtWidgets.QFrame(self.timePage)
        self.MainInputFrame.setMinimumSize(QtCore.QSize(500, 0))
        self.MainInputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainInputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainInputFrame.setObjectName("MainInputFrame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.MainInputFrame)
        self.verticalLayout_16.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_4 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.txtID = QtWidgets.QLineEdit(self.frame_4)
        self.txtID.setMinimumSize(QtCore.QSize(0, 42))
        self.txtID.setStyleSheet("\n"
"#txtID {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid transparent;  /* Initially, set a transparent border */\n"
"}\n"
"\n"
"#txtID:focus {\n"
"    border: 2px solid rgb(85, 170, 255);  /* Change the border color when the button is focused/clicked */\n"
"}")
        self.txtID.setObjectName("txtID")
        self.horizontalLayout_7.addWidget(self.txtID)
        self.verticalLayout_16.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.txtWO = QtWidgets.QLineEdit(self.frame_5)
        self.txtWO.setMinimumSize(QtCore.QSize(0, 42))
        self.txtWO.setStyleSheet("\n"
"#txtWO {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid transparent;  /* Initially, set a transparent border */\n"
"}\n"
"\n"
"#txtWO:focus {\n"
"    border: 2px solid rgb(85, 170, 255);  /* Change the border color when the button is focused/clicked */\n"
"}")
        self.txtWO.setObjectName("txtWO")
        self.horizontalLayout_8.addWidget(self.txtWO)
        self.verticalLayout_16.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.txtPT = QtWidgets.QLineEdit(self.frame_6)
        self.txtPT.setMinimumSize(QtCore.QSize(0, 42))
        self.txtPT.setStyleSheet("\n"
"#txtPT {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid transparent;  /* Initially, set a transparent border */\n"
"}\n"
"\n"
"#txtPT:focus {\n"
"    border: 2px solid rgb(85, 170, 255);  /* Change the border color when the button is focused/clicked */\n"
"}")
        self.txtPT.setObjectName("txtPT")
        self.horizontalLayout_9.addWidget(self.txtPT)
        self.verticalLayout_16.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.txtIssue = QtWidgets.QLineEdit(self.frame_7)
        self.txtIssue.setMinimumSize(QtCore.QSize(0, 42))
        self.txtIssue.setStyleSheet("\n"
"#txtIssue {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid transparent;  /* Initially, set a transparent border */\n"
"}\n"
"\n"
"#txtIssue:focus {\n"
"    border: 2px solid rgb(85, 170, 255);  /* Change the border color when the button is focused/clicked */\n"
"}")
        self.txtIssue.setObjectName("txtIssue")
        self.horizontalLayout_10.addWidget(self.txtIssue)
        self.verticalLayout_16.addWidget(self.frame_7)
        self.frame_3 = QtWidgets.QFrame(self.MainInputFrame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.btnSaveRecord = QtWidgets.QPushButton(self.frame_3)
        self.btnSaveRecord.setMinimumSize(QtCore.QSize(170, 35))
        self.btnSaveRecord.setMaximumSize(QtCore.QSize(170, 16777215))
        self.btnSaveRecord.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSaveRecord.setStyleSheet("\n"
"#btnSaveRecord{\n"
"\n"
"background-color:rgb(85, 170, 255);\n"
"font: 75 12pt \"Arial\";\n"
"color:white;\n"
"}\n"
"#btnSaveRecord:hover {\n"
"background-color:#4673c6;\n"
"}")
        self.btnSaveRecord.setObjectName("btnSaveRecord")
        self.verticalLayout_17.addWidget(self.btnSaveRecord)
        self.verticalLayout_16.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.MainInputFrame, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.timePage)
        self.verticalLayout_15.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.pagesContainer)
        self.extraRightBox = QtWidgets.QFrame(self.content)
        self.extraRightBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraRightBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraRightBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraRightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraRightBox.setObjectName("extraRightBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.extraRightBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.themeSettingsTopDetail = QtWidgets.QFrame(self.extraRightBox)
        self.themeSettingsTopDetail.setMaximumSize(QtCore.QSize(16777215, 3))
        self.themeSettingsTopDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.themeSettingsTopDetail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.themeSettingsTopDetail.setObjectName("themeSettingsTopDetail")
        self.verticalLayout_7.addWidget(self.themeSettingsTopDetail)
        self.contentSettings = QtWidgets.QFrame(self.extraRightBox)
        self.contentSettings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentSettings.setObjectName("contentSettings")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.contentSettings)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.topMenus = QtWidgets.QFrame(self.contentSettings)
        self.topMenus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenus.setObjectName("topMenus")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.topMenus)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btn_message = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_message.sizePolicy().hasHeightForWidth())
        self.btn_message.setSizePolicy(sizePolicy)
        self.btn_message.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_message.setFont(font)
        self.btn_message.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_message.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_message.setStyleSheet("background-image: url(:/icons/images/icons/cil-envelope-open.png);")
        self.btn_message.setObjectName("btn_message")
        self.verticalLayout_14.addWidget(self.btn_message)
        self.btn_print = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_print.sizePolicy().hasHeightForWidth())
        self.btn_print.setSizePolicy(sizePolicy)
        self.btn_print.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_print.setFont(font)
        self.btn_print.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_print.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_print.setStyleSheet("background-image: url(:/icons/images/icons/cil-print.png);")
        self.btn_print.setObjectName("btn_print")
        self.verticalLayout_14.addWidget(self.btn_print)
        self.btn_logout = QtWidgets.QPushButton(self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logout.sizePolicy().hasHeightForWidth())
        self.btn_logout.setSizePolicy(sizePolicy)
        self.btn_logout.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_logout.setFont(font)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_logout.setStyleSheet("background-image: url(:/icons/images/icons/cil-account-logout.png);")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_14.addWidget(self.btn_logout)
        self.verticalLayout_13.addWidget(self.topMenus, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.contentSettings)
        self.horizontalLayout_4.addWidget(self.extraRightBox)
        self.verticalLayout_6.addWidget(self.content)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.appMargins.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLeftApp.setText(_translate("MainWindow", "Auto Post"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#4673c6;\">H</span></p></body></html>"))
        self.extraLabel.setText(_translate("MainWindow", "Left Box"))
        self.extraCloseColumnBtn.setToolTip(_translate("MainWindow", "Close left box"))
        self.btn_share.setText(_translate("MainWindow", "Share"))
        self.btn_adjustments.setText(_translate("MainWindow", "Adjustments"))
        self.btn_more.setText(_translate("MainWindow", "More"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ff79c6;\">PyDracula</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">An interface created using Python and PySide (support for PyQt), and with colors based on the Dracula theme created by Zeno Rocha.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">MIT License</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#bd93f9;\">Created by: Wanderson M. Pimenta</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ff79c6;\">Convert UI</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#ffffff;\">pyside6-uic main.ui &gt; ui_main.py</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ff79c6;\">Convert QRC</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#ffffff;\">pyside6-rcc resources.qrc -o resources_rc.py</span></p></body></html>"))
        self.titleRightInfo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#4673c6;\">HIMOINSA</span><span style=\" color:#ffffff;\"> - A Yanmar Company</span></p></body></html>"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "Close"))
        self.btnUpdate.setText(_translate("MainWindow", "Update"))
        self.label_2.setText(_translate("MainWindow", "ID:   "))
        self.txtID.setPlaceholderText(_translate("MainWindow", "Enter ID"))
        self.label_3.setText(_translate("MainWindow", "WO: "))
        self.txtWO.setPlaceholderText(_translate("MainWindow", "Enter Work Order"))
        self.label_4.setText(_translate("MainWindow", "PT:   "))
        self.txtPT.setPlaceholderText(_translate("MainWindow", "Enter PT"))
        self.label_5.setText(_translate("MainWindow", "Issue:"))
        self.txtIssue.setPlaceholderText(_translate("MainWindow", "Enter any Issue"))
        self.btnSaveRecord.setText(_translate("MainWindow", "Start"))
        self.btn_message.setText(_translate("MainWindow", "Message"))
        self.btn_print.setText(_translate("MainWindow", "Print"))
        self.btn_logout.setText(_translate("MainWindow", "Logout"))
import resorces_rc
